#!/bin/sh

# Debug
# set -x

# Tell the user we run a pre-commit hook
echo 'Running pre-commit hook'

# Old version
OLD_VERSION=$(cat VERSION)
echo 'Current version:' $OLD_VERSION

# Build new version string
MAJOR=$(date +%y | cut -c1)
MINOR=$(date +%y | cut -c2)
DAY=$(date +%j)
COMMIT=$((`git rev-list --count --since=midnight HEAD` + 1))
VERSION=$MAJOR.$MINOR.$DAY.$COMMIT

# Update version file
echo 'Updating project version to:' $VERSION
echo $VERSION > VERSION

# Add version file to commit
echo 'Adding new version to commit'
echo
git add VERSION

# Interrupt, so user can see output before commit
read -p "Press any key to continue..." </dev/tty
echo
